version: "3.7"

services:
    app:
        deploy:
            resources:
                limits:
                    memory: 500M
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: backend
            SERVICE_TAGS: backend
        working_dir: /usr/src/app
        volumes:
            - ./:/usr/src/app
        ports:
            - "80:80"
            - "443:443"
        networks:
            - my-net
networks:
    my-net:
        driver: bridge